### PR TITLE
don't break on empty bodies (empty posts)

### LINKED ISSUE #25: Cannot set property 'files'
TypeError: Cannot set property 'files' of undefined
      at handleRequest .../node_modules/koa-better-body/index.js:125:23)

It can be changed to better

```
returns = returns || {};
returns[filesKey] = cache.files;
```

### PR DESCRIPTION
**Pull request by sedenardi**
Fixes #25.

Posting empty bodies should be allowed, as it's a valid use case (for /Logout and such).

### CODE REVIEW

**Comment by tunnckoCore** [comment]
I remember this check was intentional. Why use POST for logout? I think it can be just like a button that redirect to some GET route and destroy the session.

**Comment by sedenardi** [comment]
Some browsers will prefetch any `GET` requests, causing unintentional logouts (I've experienced this firsthand with IE).

SO reference: http://stackoverflow.com/a/14587231/3311526

Another potential fix would be @isdenya's initial suggestion of changing L129 and L132 from 
`returns = cache.fields;` 
to 
`returns = cache.fields || {};`

**Comment by tunnckoCore** [comment]
Hm, good point. Okey, I'll merge now and will publish patch version later this evening.

**Comment by sedenardi** [comment]
Cool. Thanks @tunnckoCore

**Comment by tunnckoCore** [comment]
Damn that wildcard devDeps :rage: I'll come to it tomorrow, sorry.

edit: It's hell strange how [v0.11.16 fails with "no internal promise"](https://travis-ci.org/tunnckoCore/koa-better-body/jobs/120683801) and force me to use some tricks and shits... but nevermind.
That's why I don't want to merge and do fixes and such things - it's too old, too outdated, too bad workflow / boilerplate and scripts - these koa/express packages are since I came to node and didn't get big update, yet. I want to rewrite it completely from scratch.

**Pull request merged**
