### PR TITLE
[BF] remove ctx.querystring when getting qs module from koa

### PR DESCRIPTION
**Pull request by wisdom-yzh**
a simple way to solve the issue [https://github.com/tunnckoCore/koa-better-body/issues/77#issuecomment-272590756](https://github.com/tunnckoCore/koa-better-body/issues/77#issuecomment-272590756)

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@wisdom-yzh great and thanks!

I just don't know when can release next version (probably on week or two), but everyone can use the master branch without problems.

**Comment by jeanru** [comment]
Have the same problem with this and fixed it by add following scripts in src/apps/index.js:
const qs = require('querystring')
app.querystring = qs

**Comment by tunnckoCore** [comment]
Hey, @jeanru, thank you! But it's fixed by merging this PR and is released as v3 i believe.

Is it still a problem or what?

edit:

from utils.js 
```js
  ctx.app.querystring =
    opts.querystring ||
    opts.qs || // alias
    (ctx.app && ctx.app.querystring) ||
    (ctx.app && ctx.app.qs) || // alias
    ctx.qs // alias
```

Even if you pass it through options, we care about that to assign it to `app.querystring`, so shouldn't be a problem.

**Comment by jeanru** [comment]
No, everything works well now.  The version of qs which I used is 2.4.2. 
Maybe I will try to upgrade to v3.

**Comment by tunnckoCore** [comment]
Great, try and ping if you need some help to lead you! I'm here.

**Comment by jeanru** [comment]
OK, thank you.

**Pull request merged**
